name: Upload GodotSteam artifact


description: Upload the GodotSteam artifact


inputs:
  name:
    description: The artifact name
    default: "${{ github.job }}"

  path:
    description: The path to upload
    required: true
<<<<<<< HEAD
    default: "bin/"
=======
    default: "./bin/"


>>>>>>> 39d3d9276f65d6112e4d428dcbc4876cefc853a5
runs:
  using: "composite"

  steps:
    - name: Upload GodotSteam Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        overwrite: true
        retention-days: 14